### ISSUE TITLE
Please upload the latest version of the library to PyPI.

### ISSUE THREAD

**Issue by tetsuzawa** [hoechenberger/questplus#42]
Hello. I am using the 2019.4 version of the QUEST+ library for my psychometric experiments.

However, I am having trouble with a bug in the psychometric function (norm_pdf).

This bug seems to have been resolved in the latest commit (9e1d0b8), so I would like you to upload this version of the QUEST+ library to PyPI.

Thank you for implementing this great software.

**Comment by hoechenberger** [comment]
Hello @tetsuzawa,

I can make a release this weekend – could you kindly remind me in case I forget? ;)

In the meantime, you can install the `master` branch using `pip` via:

```
pip install -U https://github.com/hoechenberger/questplus/archive/master.zip
```

**Comment by tetsuzawa** [comment]
@hoechenberger 

> I can make a release this weekend – could you kindly remind me in case I forget? ;)

Of course!

> In the meantime, you can install the master branch using pip via:
> `pip install -U https://github.com/hoechenberger/questplus/archive/master.zip`

This command worked correctly and solved the problem.

Thank you for your reply and information.

**Comment by hoechenberger** [comment]
Done.
